scrape_configs:
  - job_name: 'spring-boot-kafka'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'kafka-exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9308']