name: qdrant
services:
  # Vector database for storing document content: http://localhost:6333/dashboard
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    env_file:
      - .env
    environment:
      # Set your API Key (virtual password) in .env file.
      - QDRANT__SERVICE__API_KEY=${QDRANT__SERVICE__API_KEY}
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: