spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_starter_postgres
    username: db_user
    password: db_pwd
  mail:
    host: your-mail-server.com
    port: 465
    username: admin@your-mail-server.com
    password: mail_pwd
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: local_jobs
    password: rabbit_pwd
  kafka:
    bootstrap-servers: host.docker.internal:9092
  data:
    redis:
      host: host.docker.internal
      port: 6379
      password: redis_pwd
app:
  secret: jwt_secret
  cron:
    enable: true
