package com.bekaku.api.spring.serviceImpl;


import com.bekaku.api.spring.service.RestClientService;
import com.google.gson.JsonObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.client.JdkClientHttpRequestFactory;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestClient;

import java.net.http.HttpClient;
import java.time.Duration;
import java.util.HashMap;

@Service
public class RestClientServiceImpl implements RestClientService {

    private final RestClient restClient;

    @Autowired
    public RestClientServiceImpl() {
        HttpClient javaHttpClient = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(10))
                .build();
        JdkClientHttpRequestFactory factory = new JdkClientHttpRequestFactory(javaHttpClient);
        factory.setReadTimeout(Duration.ofSeconds(30));
        this.restClient = RestClient.builder()
                .requestFactory(factory)
                .build();
    }

    /*

    public record PostResponse(
        int id,
        int userId,
        String title,
        String body
    ) {}

    public record CreatePostRequest(
        int userId,
        String title,
        String body
    ) {}

    CreatePostRequest payload = new CreatePostRequest(
                1,
                "My New Post",
                "This is the content generated by RestClient"
        );

    HashMap<String, String> headers = ConstantData.defaultHttpHeaders();
    headers.put(Authorization, "Bearer VKFcW);
    UserResponse newUser = restService.post("https://api.example.com/users", payload, headers, UserResponse.class);
     */
    @Override
    public <T> T post(String url, Object body, HashMap<String, String> headers, Class<T> responseType) {
        Object requestBody = body != null ? body : new java.util.HashMap<>();

        return restClient.post()
                .uri(url)
                .contentType(MediaType.APPLICATION_JSON)
                .headers(httpHeaders -> {
                    if (headers != null) {
                        headers.forEach(httpHeaders::add);
                    }
                })
                .body(requestBody)
                .retrieve()
                .body(responseType);
    }

    /*
    HashMap<String, String> headers = ConstantData.defaultHttpHeaders();
    headers.put(Authorization, "Bearer VKFcW);
    UserResponse user = restService.get("https://api.example.com/users/1", headers, UserResponse.class);
     */
    @Override
    public <T> T get(String url, HashMap<String, String> headers, Class<T> responseType) {
        return restClient.get()
                .uri(url)
                .headers(httpHeaders -> {
                    if (headers != null) {
                        headers.forEach(httpHeaders::add);
                    }
                })
                .retrieve()
                .body(responseType);
    }

    @Override
    public <T> T delete(String url, HashMap<String, String> headers, Class<T> responseType) {
        return restClient.delete()
                .uri(url)
                .headers(httpHeaders -> {
                    if (headers != null) {
                        headers.forEach(httpHeaders::add);
                    }
                })
                .retrieve()
                .body(responseType);
    }
}
