name: Build GraalVM Native Image

# Specify when the code should run (e.g., when pushing code to the main branch).
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Manual execution is permitted on the GitHub website.

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use Ubuntu as a GitHub runner (fast and free).

    steps:
      # 1. Pull the latest source code.
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Install Docker Buildx (required for using --mount=type=cache in the Dockerfile).
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./DockerfileNative
          push: true # Change to true if you want to push to the Registry (e.g., Docker Hub).
          tags: |
            baekaku/spring-api-native:latest
            baekaku/spring-api-native:${{ github.sha }}
          # 4. Magical caching! Let GitHub cache your Gradle and GraalVM builds across build iterations.
          cache-from: type=gha
          cache-to: type=gha,mode=max